package config

// This is the config for ~/.rect/config.toml NOT for individual projects.
// For the project config please visit projectManager/config.
// A default version of this config is generated by NewConfig() of the config package.
type (
	Config struct {
		User     UserConfig     `toml:"user"`
		Licenses LicenseConfig  `toml:"licences"`
		Compiler CompilerConfig `toml:"compiler"`
		Template TemplateConfig `toml:"templates"`
	}

	UserConfig struct {
		Author string
		Email  string
	}

	LicenseConfig struct {
		Default        string
		Location       string
		DownloadSource string
	}

	CompilerConfig struct {
		Preference       string
		PackagesLocation string
	}

	TemplateConfig struct {
		Default        string
		Location       string
		Standards      []string
		DownloadSource string
	}
)
