package config

// This is the ProjectConfig for ~/.rect/ProjectConfig.toml NOT for individual projects.
// For the project ProjectConfig please visit projectManager/ProjectConfig.
// A default version of this ProjectConfig is generated by NewConfig() of the ProjectConfig package.
type (
	Config struct {
		User     UserConfig     `toml:"user"`
		Licenses LicenseConfig  `toml:"licences"`
		Compiler CompilerConfig `toml:"compiler"`
		Template TemplateConfig `toml:"templates"`
	}

	UserConfig struct {
		Author string
		Email  string
	}

	LicenseConfig struct {
		Default        string
		Location       string
		DownloadSource string
	}

	CompilerConfig struct {
		Preference       string
		PackagesLocation string
	}

	TemplateConfig struct {
		Default        string
		Location       string
		Standards      []string
		DownloadSource string
	}
)
