name: Rust

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Clean
      run: rm ./target/debug/rectx/test -rf
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Help menu
      run: ./target/debug/rectx --help
    - name: Create project
      run: ./target/debug/rectx new test
    - name: Build project
      run: cd ./target/debug/test && ../rectx build
    - name: Run project
      run: ../rectx run
