# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '26 16 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Due to a lack of activity, this issue has been deemed stale. If this level of activity continues for a further 5 days this issues will be closed.'
        close-issue-message: 'This issue has been closed due to a lack of activity!'
        stale-pr-message: 'Due to a lack of activity, this pull request has been deemed stale. If this level of activity continues for a further 5 days this pull request will be closed.'
        close-pr-message: 'This pull request has been closed due to a lack of activity!'
        stale-issue-label: 'Stale issue'
        stale-pr-label: 'Stale pull request'
        days-before-stale: 14
        days-before-close: 5
